version: "3.7"

services:
  server:
    build: .
    image: rcm-server
    container_name: rcm-server-cont
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      database:
        condition: service_healthy

  client:
    build: client/
    image: rcm-client
    container_name: rcm-client-cont
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_healthy

  database:
    image: mariadb:11.0
    container_name: rcm_db
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mariadb --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rcmdb

  adminer:
    image: adminer
    container_name: rcm_adminer
    ports:
      - "8081:8080"
